import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";
import { getVideos, getPopularVideos } from "../lib/videos";
import { startFetchMyQuery } from "../lib/db/hasura";

export async function getServerSideProps() {
  const surfingVideos = await getVideos("surfing");
  const sportsVideos = await getVideos("sports");
  const popularVideos = await getPopularVideos();
  const cookingVideos = await getVideos("cooking");

  return {
    props: { surfingVideos, sportsVideos, popularVideos, cookingVideos },
  };
}

export default function Home({
  surfingVideos,
  sportsVideos,
  popularVideos,
  cookingVideos,
}) {
  startFetchMyQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="joe@joe.com" />
        <Banner
          videoId="T_WSXXPQYeY"
          title="Back to the future"
          subtitle="A classic from the 80's"
          imgUrl="/static/back_to_the_future.jpg"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Surfing" videos={surfingVideos} size="large" />
          <SectionCards title="Sports" videos={sportsVideos} size="medium" />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
          <SectionCards title="Cooking" videos={cookingVideos} size="medium" />
        </div>
      </div>
    </div>
  );
}
