import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import Card from "../components/card/card";
import SectionCards from "../components/card/section-cards";

export default function Home() {
  const disneyVideos = [
    {
      imgUrl: "/static/back_to_the_future.jpg",
    },
    {
      imgUrl: "/static/back_to_the_future.jpg",
    },
    {
      imgUrl: "/static/back_to_the_future.jpg",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="joe@joe.com" />
      <Banner
        title="Back to the future"
        subtitle="A classic from the 80's"
        imgUrl="/static/back_to_the_future.jpg"
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
      </div>
    </div>
  );
}
