import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Nextflix</h1>

      {/* <NavBar /> */}
      <Banner
        title="Back to the future"
        subtitle="A classic from the 80's"
        imgUrl="/static/back_to_the_future.jpg"
      />
      {/* <Card /> */}
    </div>
  );
}
